### PR TITLE
GT-58

### PR DESCRIPTION
**Pull request by ryancarlson**
This branch has turned into a psuedo "dev" branch, with many updates in it.  Top ones include:
 - preventing errors generated by cache interactions' failing from breaking actual user tasks.  code will continue on as if the requested record was not in the cache
 - Better error reporting from cache implementation - things are no longer reported to standard error
 - Image filenames are no longer hashed.  it made content updates really difficult and provided no perceivable value
 - Created endpoints for altering the structure of a specific language (drafts only) and the global altering of content across all translations
 - Deleted some old data migration files
 - Environments can now turn integration with onesky on or off (useful for local development or on stage)

### CODE REVIEW

**Comment by ryancarlson** [comment]
@mattfred There a few different changes in this PR.. it kind of became a dev branch for things I worked on here and there.  I think I've listed them all out in the description.  Can you take a look please?

**Comment by michaelharro** [comment]
Now that the image file names are not hashed are the file names still unique across all packages and languages? On the client side all files are stored in a single folder so if Satisfied and KGP both use the file name 1.png then the first package will have it's image overwritten unless we have globally unique names or we rewrite how the clients store their files.

**Comment by ryancarlson** [comment]
@michaelharro I didn't think it did cause any conflicts until I checked the thumbnails.  the 4laws thumbnails are rendered for kgp now.  the rest of the images seem to be correctly unique. i'll see if there's a way to fix the thumbnails

**Comment by michaelharro** [comment]
@ryancarlson As long as you have a way of keeping the filenames unique you are fine. The only thing that hashes offered on top of uniqueness is optimisation but correctness is more important than optimisation. I assume removing hashes makes things simpler.

**Comment by mattfred** [comment]
The rest looks fine.

**Comment by ryancarlson** [comment]
@mattfred addressed your feedback and added a couple more changes.

**Comment by mattfred** [comment]
LGTM

**Comment by ryancarlson** [comment]
Thanks!

**Pull request merged**
