### PR TITLE
Webapp endpoints

### PR DESCRIPTION
**Pull request by ryancarlson**
Adds endpoints that are required by a God Tools webapp that is to be developed.
New endpoints include:
 - GET: translations/{langaugeCode}/{packageCode}/config
   - returns in JSON an array of pages that compose a God Tools package in a specific language
   - filenames of the requested pages are included
 - GET: translations/{langaugeCode}/{packageCode}/pages/{pageId}
   - returns in JSON format an map (key/value pairs) of translated strings for a specific page, translated to a specific language
   - this assumes that the webapp will know where the text should go based on its ID.  those who are developing the webapp know this.

### CODE REVIEW

**Comment by ryancarlson** [comment]
example config:
````json
{
    "packageName": {
        "title": "Knowing God Personally"
    },
    "pageSet": [
        {
            "title": "Home",
            "filename": "42b05b84-6752-4905-b47f-c9b38fe6ef83.xml"
        },
        {
            "title": "1 God Loves You And Created You To Know Him Personally.",
            "filename": "49aabd78-c728-4cbb-a939-4fd7268135bb.xml"
        },
        {
            "title": "2 We Are Separated From God By Our Sin, So We Cannot Know Him Or Experience His Love.",
            "filename": "6ef7bb84-76d8-484d-b571-5d2928d50bc6.xml"
        },
        {
            "title": "3 Jesus Is God's Only Solution For Our Sin. Only Through Him Can We Know God And Receive His Love And Forgiveness.",
            "filename": "bba23be1-2fb2-4616-807b-c2d837358b6e.xml"
        },
        {
            "title": "4 We Must Each Respond To Jesus By Placing Our Trust In Him As Our Saviour And Lord. Only Then Can We Know God Personally.",
            "filename": "cd3f9b23-149b-438c-8c50-f03816307ee9.xml"
        },
        {
            "title": "These Circles Describe Two Types Of People",
            "filename": "6e0edeff-db8e-432d-b041-158a0d165550.xml"
        },
        {
            "title": "To Begin A Relationship With God, You Must Give Jesus Everything.",
            "filename": "6a0804e7-e720-4302-9b3a-834bb89abbcf.xml"
        },
        {
            "title": "You Can Express Your Attitude Toward God Through Prayer.",
            "filename": "e4165329-a017-453a-b6c8-2e42ec898cdd.xml"
        },
        {
            "title": "What Happens When You Put Your Trust In Jesus?",
            "filename": "6c18fd6f-4730-44c8-8f03-3cc43306d396.xml"
        },
        {
            "title": "If You Asked Jesus Into Your Life As Saviour And Lord, Many Things Have Happened, Including:",
            "filename": "09970a11-eff6-434c-a99e-e5c378439662.xml"
        },
        {
            "title": "How Can You Be Sure That All This Has Really Happened?",
            "filename": "a656863c-abf2-4c96-ba7e-97b8b5c3f756.xml"
        },
        {
            "title": "How To Grow As A Follower Of Jesus",
            "filename": "d34a3d24-23e5-4665-a401-af962cecba48.xml"
        },
        {
            "title": "Websites To Assist You",
            "filename": "10b9d34d-5816-4c60-a2d0-a77cb38a399d.xml"
        }
    ],
    "about": {
        "title": "About",
        "filename": ""
    }
}
````

**Comment by ryancarlson** [comment]
example page:
````json
{
    "translatedStrings": {
        "04fb1daf-6990-4153-9f60-7cf793a1e79b": "(Hebrews 13:5)",
        "fcea282c-75f3-4fbc-b1cd-e7e229390ec3": "But how do we know this\nactually happened?",
        "d4a4a53d-d84e-4463-8394-1ed0c3b60095": "Your Sins Have Been Forgiven",
        "fa829ea2-0ce4-4a97-8b26-79bfbb93733e": "You Have Been Empowered",
        "8ae60223-9586-4dca-96ee-1c3c01614eef": "All your sins have been forgiven.",
        "a63a4ef6-d990-4ca7-9f68-e22e168d1cf7": "(John 17:3)",
        "7acd2e78-76ab-4b26-a286-51466da85107": "You have started a friendship with God that will last forever.",
        "02ae9b80-acdf-4f58-af8a-a33ad348bf4e": "You Are Now Friends with God",
        "d9b98feb-50ca-4a60-ae9e-435c3849c276": "IF YOU ASKED JESUS INTO YOUR LIFE AS SAVIOUR AND LORD, MANY THINGS HAVE HAPPENED, INCLUDING:",
        "f9e251ac-2de8-4e31-a7eb-e6e656b129e0": "(Colossians 1:13-14)",
        "890268cf-4d0f-4b0c-ae62-8efb54f724b2": "(2 Corinthians 5:17; Ephesians 3:14-21)",
        "a2e2e777-39f0-4e59-a427-bcae73a93ef5": "Jesus Has Come Into Your life",
        "5302c48f-e424-4a87-8f1b-5ce617a8aa8c": "Jesus has come into your life by the Holy Spirit and he will never leave you.",
        "9cb35a1d-04fb-4172-9752-63a8f52012b0": "You have become a child of God. He is your heavenly father.",
        "b61c767f-ef3c-4a5a-bdfb-3d660dea67ff": "God has given you new power to live a transformed life.",
        "fae8031d-d8fe-498e-9d2f-c8c3147bc26a": "(Galatians 3:26)",
        "d754b66e-f4e6-4bd4-9764-af8b50e0f531": "You Are Now a Child of God"
    }
}
````

**Comment by ryancarlson** [comment]
@mattfred can you review this please?

**Comment by mattfred** [comment]
This looks good.

**Comment by ryancarlson** [comment]
@mattfred , removed the XML method that duplicated code.  how's it looking now?

**Comment by mattfred** [comment]
This looks good.

**Pull request merged**
